import { useCallback, useEffect, useMemo, useState } from "react";
import { createAdminNavigationRepository, emptyAdminNavigationItem, type AdminNavigationItem, type AdminNavigationSnapshot } from "./repository";
import { navigationDestinationTypes } from "../../navigation/types";

function NavigationCard({ item, categories, busy, onChange, onSave, onDelete }: { item: AdminNavigationItem; categories: AdminNavigationSnapshot["categories"]; busy: boolean; onChange: (item: AdminNavigationItem) => void; onSave: () => void; onDelete: () => void }) {
  const update = <K extends keyof AdminNavigationItem>(key: K, value: AdminNavigationItem[K]) => onChange({ ...item, [key]: value });
  return <article className="admin-operation-card"><header><div><strong>{item.id ? item.stableCode : "Menu item mới"}</strong><small>{item.destinationType}</small></div><label className="admin-check admin-check--compact"><input type="checkbox" checked={item.active} onChange={(event) => update("active", event.target.checked)} /><span>Đang bật</span></label></header><div className="admin-field-grid admin-field-grid--three"><label>Mã ổn định<input required disabled={Boolean(item.id)} value={item.stableCode} onChange={(event) => update("stableCode", event.target.value.toLowerCase().trim())} /></label><label>Đích đến<select value={item.destinationType} onChange={(event) => { const destinationType = event.target.value as AdminNavigationItem["destinationType"]; onChange({ ...item, destinationType, categoryId: destinationType === "CATEGORY" ? item.categoryId : null, externalUrl: destinationType === "EXTERNAL" ? item.externalUrl : "" }); }}>{navigationDestinationTypes.map((type) => <option value={type} key={type}>{type}</option>)}</select></label><label>Thứ tự<input type="number" min={0} step={1} value={item.sortOrder} onChange={(event) => update("sortOrder", Number(event.target.value))} /></label>{item.destinationType === "CATEGORY" && <label>Category<select required value={item.categoryId ?? ""} onChange={(event) => update("categoryId", event.target.value || null)}><option value="">Chọn Category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>}{item.destinationType === "EXTERNAL" && <label className="admin-field-span">HTTPS URL<input type="url" value={item.externalUrl} placeholder="https://example.com" onChange={(event) => update("externalUrl", event.target.value.trim())} /></label>}<label>Nhãn VI<input required value={item.viLabel} onChange={(event) => update("viLabel", event.target.value)} /></label><label>Nhãn KO<input required value={item.koLabel} onChange={(event) => update("koLabel", event.target.value)} /></label></div><div className="admin-editor-actions"><button className="admin-button admin-button--primary" type="button" disabled={busy} onClick={onSave}>{busy ? "Đang lưu…" : "Lưu menu item"}</button>{item.id && <button className="admin-button admin-button--secondary" type="button" disabled={busy} onClick={onDelete}>Xoá</button>}</div></article>;
}

export function AdminNavigationPage() {
  const repository = useMemo(() => createAdminNavigationRepository(), []);
  const [snapshot, setSnapshot] = useState<AdminNavigationSnapshot | null>(null);
  const [draft, setDraft] = useState(() => emptyAdminNavigationItem());
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const load = useCallback(async () => { try { const next = await repository.getSnapshot(); setSnapshot(next); setDraft(emptyAdminNavigationItem((next.items.length + 1) * 10)); } catch { setNotice({ tone: "error", text: "Không thể tải Navigation." }); } }, [repository]);
  useEffect(() => { document.title = "Navigation — Luméa Admin"; void load(); }, [load]);
  const save = async (item: AdminNavigationItem) => { const key = item.id ?? "new"; setBusy(key); try { await repository.save(item); await load(); setNotice({ tone: "success", text: "Đã lưu Navigation và nhãn VI/KO." }); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "Không thể lưu Navigation." }); } finally { setBusy(null); } };
  const remove = async (item: AdminNavigationItem) => { if (!item.id || !window.confirm(`Xoá menu item “${item.viLabel}”?`)) return; setBusy(item.id); try { await repository.remove(item.id); await load(); setNotice({ tone: "success", text: "Đã xoá menu item." }); } catch { setNotice({ tone: "error", text: "Không thể xoá menu item." }); } finally { setBusy(null); } };
  const move = async (index: number, offset: -1 | 1) => { if (!snapshot) return; const target = index + offset; if (target < 0 || target >= snapshot.items.length) return; const ordered = [...snapshot.items]; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; setBusy("order"); try { await repository.reorder(ordered.map((item) => item.id!)); await load(); setNotice({ tone: "success", text: "Đã lưu thứ tự Navigation." }); } catch { setNotice({ tone: "error", text: "Không thể đổi thứ tự Navigation." }); } finally { setBusy(null); } };
  if (!snapshot) return <section className="admin-page" aria-busy="true"><div className="admin-empty">{notice?.text ?? "Đang tải Navigation…"}</div></section>;
  return <section className="admin-page"><header className="admin-page-heading"><span className="admin-kicker">STOREFRONT</span><h1>Navigation</h1><p>Chỉ các đích nội bộ được hỗ trợ hoặc HTTPS URL an toàn. Không nhập route tùy ý.</p></header>{notice && <div className={`admin-alert admin-alert--${notice.tone}`} role={notice.tone === "error" ? "alert" : "status"}>{notice.text}</div>}<section className="admin-editor-section"><header><span>01</span><div><h2>Tạo menu item</h2><p>Nhãn VI/KO và đích đến là bắt buộc.</p></div></header><NavigationCard item={draft} categories={snapshot.categories} busy={busy === "new"} onChange={setDraft} onSave={() => void save(draft)} onDelete={() => undefined} /></section><section className="admin-editor-section"><header><span>02</span><div><h2>Menu hiện tại</h2><p>Storefront đọc trạng thái và thứ tự này sau refresh.</p></div></header><div className="admin-operations-list">{snapshot.items.map((item, index) => <div key={item.id}><div className="admin-row-actions"><button type="button" disabled={Boolean(busy) || index === 0} onClick={() => void move(index, -1)}>↑</button><button type="button" disabled={Boolean(busy) || index === snapshot.items.length - 1} onClick={() => void move(index, 1)}>↓</button></div><NavigationCard item={item} categories={snapshot.categories} busy={busy === item.id} onChange={(next) => setSnapshot((current) => current ? { ...current, items: current.items.map((value) => value.id === item.id ? next : value) } : current)} onSave={() => void save(item)} onDelete={() => void remove(item)} /></div>)}</div></section></section>;
}
